[crate_roots]
mnist_nn = "/Users/raphaeldoukhan/Desktop/Cairo/Giza/orion_tutorials/mnist_nn/src"
orion = "/Users/raphaeldoukhan/Library/Caches/com.swmansion.scarb/registry/git/checkouts/orion-PS5FVI1VTTS96/082405b/src"

